//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminCoop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int id_account { get; set; }
        public string Full_name { get; set; }
        public string Phone { get; set; }
        public int Cabinet { get; set; }
        public int Network_status { get; set; }
        public string Photo { get; set; }
    }
}
