//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminCoop
{
    using System;
    using System.Collections.Generic;
    
    public partial class cabinet
    {
        public int Id_cabinet { get; set; }
        public double area { get; set; }
        public int floor { get; set; }
        public int status { get; set; }
        public int id_account { get; set; }
        public Nullable<int> number { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
